### ISSUE TITLE
extract 14class for mimic-crx

### ISSUE THREAD

**Issue by catfish132** [mlmed/torchxrayvision#105]
I want to use this codebase to predict pic in mimic-crx with 14 classes of diseases , how should I do?
I find all the model out put a 18dim feature ,and many of the dim ===0.

**Comment by catfish132** [comment]
I tried ，but get still 18 classes. Not 14 classes.
![image](https://user-images.githubusercontent.com/56590427/191882980-cbcb19fb-130c-41d0-8138-59f0e48ed447.png)

**Comment by ieee8023** [comment]
You can select the 14 that you want.
