### ISSUE TITLE
Example notebook doesn't work and has poor results when fixed

### ISSUE THREAD

**Issue by Htermotto** [mlmed/torchxrayvision#109]
Hi,

In using Torch XRV we started with the example [notebook](https://github.com/mlmed/torchxrayvision/blob/master/scripts/xray_models.ipynb). However, it has multiple issues such that it does not run to begin with. We were able to fix it but the results of the pretrained weights seem poor on the NIH dataset. Additionally we think there is a bug in the code that will erroneously apply sigmoid twice if apply_sigmoid=True [link.](https://github.com/mlmed/torchxrayvision/blob/master/torchxrayvision/models.py#L253)

I've opened a PR with our changes that fix the notebook [here](https://github.com/mlmed/torchxrayvision/pull/108) but we would appreciate input on the model performance.

EDIT: I cleared the notebook in the PR so there wouldn't be a lot of output, but essentially what we are seeing is very low precision on NIH res224. Here are the metrics we get generated from running the above notebook:

<img width="627" alt="image" src="https://user-images.githubusercontent.com/9905056/197296131-b0211461-4ce7-4f59-a180-6f53cb01ac06.png">

Thanks!

**Comment by ieee8023** [comment]
Hey, sorry for the delay, I will have a chance to look into this soon!

**Comment by Htermotto** [comment]
Thanks! Interested to know what you find. Curious if one of the issues is a calibration one.

**Comment by Htermotto** [comment]
Hi thanks for looking into this and fixing the double sigmoid bug!

I agree that the threshold of 0.5 is not optimal. In your code there are some custom thresholds set, and we tried using those, but it didn't seem to make a huge difference. However it could have been from the double sigmoid pushing the numbers up.

**Comment by ieee8023** [comment]
Let me know if this issue is not resolved. I'll close it for now.
