### ISSUE TITLE
Console always prints dataset statistics

### ISSUE THREAD

**Issue by pat-rig** [mlmed/torchxrayvision#113]
Hi everyone,

After having load the PadChest dataset my console prints its summary statistics for all executed commands

Looks like this:

{'Air Trapping': {0.0: 59407, 1.0: 2285},
 'Aortic Atheromatosis': {0.0: 60419, 1.0: 1273},
 'Aortic Elongation': {0.0: 56611, 1.0: 5081},
 'Atelectasis': {0.0: 59273, 1.0: 2419},
 'Bronchiectasis': {0.0: 60821, 1.0: 871},
 'Cardiomegaly': {0.0: 56305, 1.0: 5387},
 'Consolidation': {0.0: 61217, 1.0: 475},
 'Costophrenic Angle Blunting': {0.0: 59587, 1.0: 2105},
 'Edema': {0.0: 61584, 1.0: 108},
 'Effusion': {0.0: 60067, 1.0: 1625},
 'Emphysema': {0.0: 61146, 1.0: 546},
 'Fibrosis': {0.0: 61351, 1.0: 341},
 'Flattened Diaphragm': {0.0: 61379, 1.0: 313},
 'Fracture': {0.0: 60030, 1.0: 1662},
 'Granuloma': {0.0: 60135, 1.0: 1557},
 'Hemidiaphragm Elevation': {0.0: 60806, 1.0: 886},
 'Hernia': {0.0: 60704, 1.0: 988},
 'Hilar Enlargement': {0.0: 58875, 1.0: 2817},
 'Infiltration': {0.0: 57383, 1.0: 4309},
 'Mass': {0.0: 61186, 1.0: 506},
 'Nodule': {0.0: 59502, 1.0: 2190},
 'Pleural_Thickening': {0.0: 59617, 1.0: 2075},
 'Pneumonia': {0.0: 59782, 1.0: 1910},
 'Pneumothorax': {0.0: 61595, 1.0: 97},
 'Scoliosis': {0.0: 57761, 1.0: 3931},
 'Support Devices': {0.0: 60575, 1.0: 1117},
 'Tube': {0.0: 61467, 1.0: 225},
 'Tuberculosis': {0.0: 61290, 1.0: 402}}

How can I deactivate this?

Thanks a lot in advance!

**Comment by ieee8023** [comment]
You are getting the string value of a dataset object somewhere? It was meant to do fancy printing in a jupyter notebook. I should add something to detect if it is in a notebook.

https://github.com/mlmed/torchxrayvision/blob/master/torchxrayvision/datasets.py#L138

You can instead call .string() directly to avoid the printing.

**Comment by ieee8023** [comment]
#115 Resolves this. It will be in the next release though. Reopen the issue if it is not resolved.

**Comment by ieee8023** [comment]
I can't reproduce this. Can you try this on another machine and see if it still happens?

**Comment by pat-rig** [comment]
It does not happen inside a simple python console called from the shell. 
Must have something to do with PyCharm then.
