### ISSUE TITLE
Process_image return data?

### ISSUE THREAD

**Issue by darksky007** [mlmed/torchxrayvision#116]
Process_image Able to send value for each type of lesion as position [x,y,w,h1],[x,y,w,h2] for Heatmap? How to do it? Sorry we are newbies.

**Comment by ieee8023** [comment]
If I understand you right, you want to localize where in a heatmap a target was predicted? The centroid point? I can create a notebook that will generate the heatmap for a prediction and then you can process it how you like. Will that help you?

**Comment by darksky007** [comment]
Is it correct and if possible, can it be a frame for the location of the lesion? Maybe bother creating an example to see or not. Thank you.

**Comment by ieee8023** [comment]
Here is an example generating a heatmap for prediction: https://github.com/mlmed/torchxrayvision/blob/master/scripts/heatmaps.ipynb

You can work with the resulting `grads` variable to create a bounding box or centroid of the prediction attribution. Note that this attribution method is basic and very limited and it can be difficult to correctly explain the models predictions.

**Comment by darksky007** [comment]
Hi!, thank you very much for your interest in helping me understand. and learn the working principle of the system

**Comment by darksky007** [comment]
Hi, How can i know Ative TB?

**Comment by ieee8023** [comment]
There is no public model that I know of that predicts it. If you know of some work, I can integrate it into this library.

**Comment by darksky007** [comment]
Thank you for answering the question. I'm not sure if Pulmonary tuberculosis looks comparable to Lung Opacity, does it?

**Comment by ieee8023** [comment]
I am not an expert. I just found this though which seems promising: https://zindi.africa/competitions/runmila-ai-institute-minohealth-ai-labs-tuberculosis-classification-via-x-rays-challenge I searched for a model from the competition to include in this library but have not found one yet.

**Comment by darksky007** [comment]
Thank you.

**Comment by ieee8023** [comment]
Let me know if this issue is not resolved. I'll close it for now.
