### ISSUE TITLE
Error when loading NIH data set

### ISSUE THREAD

**Issue by pat-rig** [mlmed/torchxrayvision#124]
Hi,

calling 
` data = xrv.datasets.NIH_Dataset(imgpath=img_path, csvpath=csv_path, bbox_list_path=bbox_path) `
I ran into 
` TypeError: can't multiply sequence by non-int of type 'float' `
arisen from line 375 in `xrv.datasets`:
` self.csv['age_years'] = self.csv['Patient Age'] * 1.0 `

After removing the multiplication, the issue was solved. Age is now encoded as 058Y though, but I dont mind.

**Comment by ieee8023** [comment]
Where did you get the CSV file from? If you don't specify one, it will default to one that is included with the library (which is the 2020 metadata file from the NIH). You just need to specify the imgpath. The NIH dataset has it included because the data is public domain.

**Comment by pat-rig** [comment]
Ahh ok, I see.
I downloaded it manually from the link to academictorrent provided in  the class definition of  `NIH_Dataset`.
