### ISSUE TITLE
DICOM to X-Ray PNG

### ISSUE THREAD

**Issue by a-parida12** [mlmed/torchxrayvision#125]
Thank you @ieee8023 for this wonderful collection of models and dataset.

I wanted to know if there is a consideration to add a DICOM to PNG or a DICOM to read CXRs and covert it to PNG like arrays. or is it beyond the scope of the library?

I would be happy to help in contributing to such a feature.

**Comment by ieee8023** [comment]
We use pydicom for loading dicom files. It works great and is well supported. We use it here: https://github.com/mlmed/torchxrayvision/blob/836f5e151ba63c6608fac367811907fd9cab2517/torchxrayvision/datasets.py#L526

**Comment by a-parida12** [comment]
Thanks for pointing that out to me. As you it is only implemented for the `RSNA_Pneumonia_Dataset`  but my uggestion would be to implement it in the `torchxrayvision.utils` so that it can be used somewhere else in the future too. It could be in the lines of 

```python
def read_xray_dcm(path, voi_lut = True, fix_monochrome = True):
    try:
         import pydicom
         from pydicom.pixel_data_handlers.util import apply_voi_lut
    except ImportError as e:
                raise Exception("Missing Package Pydicom. ")
    dicom = pydicom.read_file(path)
    
    # LUT for human friendly view
    if voi_lut:
        data = apply_voi_lut(dicom.pixel_array, dicom)
    else:
        data = dicom.pixel_array
               
    # `MONOCHROME1` have an inverted view; Bones are black; background is white
    if fix_monochrome and dicom.PhotometricInterpretation == "MONOCHROME1":
        data = np.amax(data) - data
        
    data = data - np.min(data)
    data = data / np.max(data)
    data = (data * 255).astype(np.uint8)
        
    return data
```

It would also help remove some pitfalls like in https://github.com/mlmed/torchxrayvision/blob/836f5e151ba63c6608fac367811907fd9cab2517/torchxrayvision/datasets.py#L530
where the assumption is that the dicom `pixel_array` has a max value of 255 which may not be true.

**Comment by ieee8023** [comment]
> where the assumption is that the dicom pixel_array has a max value of 255 which may not be true.

For the files in that dataset this should be correct. But yes for other images it could not be correct so more thought has to go into adding a function in utils. I would like to add that function though. If you want to add a PR we can discuss it with the team?

**Comment by ieee8023** [comment]
>     data = data - np.min(data)
>     data = data / np.max(data)
>     data = (data * 255).astype(np.uint8)

I'm not a fan of scaling like this. I think it is better to normalize based on the bit depth. Then if an image is almost all 0's be stays almost all 0's instead of being scaled up.

**Comment by a-parida12** [comment]
That is an excellent point on scaling. I never actually thought about that during the conversion. I will try to incorporate that too.

**Comment by a-parida12** [comment]
> If you want to add a PR we can discuss it with the team?

Shall I add a PR now or shall I wait for your teams green light?

**Comment by ieee8023** [comment]
@josephdviviano @RupertBrooks @hbertrand Any feedback on this idea?

I don't know if `apply_voi_lut` is a good idea because machines are reading the images not humans so we would likely prefer the most raw image.

I also think this code should sense the bit depth and scale the images to retain as much of it as possible. 

I like the feature of checking for MONOCHROME1. I would prefer code that would raise an error if an image in an unsupported mode was passed in. So it would only return correctly transformed images.

And also if we could have some open licensed test images to add that would be processed by unit tests so we could catch any issues that would be great!

**Comment by josephdviviano** [comment]
I agree RE: Joseph's comments on the scaling.

I think `voi_lut = True` should be `False`, since the primary use of this function will be to interact with ML models.

Is this function meant to be used by ML models and people creating visualizations for notebooks? If so, I like leaving `voi_lut` here.

**Comment by hbertrand** [comment]
I agree with @josephdviviano's comment. We should leave `voi_lut`, and the default should be chosen depending on what we expect to be the main use of the function.

**Comment by a-parida12** [comment]
@ieee8023 @josephdviviano @hbertrand as I was implementing it for the pull request I had the thought that the normalization to be use used has to use case specific and should be independent of the dicom reader. Therefore, the normalization needs to be handled by the user of the function outside it.

**Comment by a-parida12** [comment]
All right I will use the existing normalize function at https://github.com/mlmed/torchxrayvision/blob/master/torchxrayvision/utils.py#L39 to normalize the image array. I can get the `maxval` based on the DCM header tag for the `HighBit` https://dicom.innolitics.com/ciods/cr-image/image-pixel/00280102. So `maxval = 2**HighBit`
