### ISSUE TITLE
Why I'm getting different results for the same image?

### ISSUE THREAD

**Issue by Moheeb77** [mlmed/torchxrayvision#128]
Hi,
I'm testing the codes for process_image.py and xray_covariate_shift_example.ipynb with the image in the tests directory 00000001_000.png

i'm getting this result from the process_image.py
{'Atelectasis': 0.5050051,
           'Cardiomegaly': 0.66009027,
           'Consolidation': 0.30575272,
           'Edema': 0.27418414,
           'Effusion': 0.40261638,
           'Emphysema': 0.5036339,
           'Enlarged Cardiomediastinum': 0.40989202,
           'Fibrosis': 0.53293407,
           'Fracture': 0.323768,
           'Hernia': 0.011924741,
           'Infiltration': 0.5154413,
           'Lung Lesion': 0.22231925,
           'Lung Opacity': 0.2772149,
           'Mass': 0.32237673,
           'Nodule': 0.5091847,
           'Pleural_Thickening': 0.5102618,
           'Pneumonia': 0.30947986,
           'Pneumothorax': 0.24847917}}

and from the other one i'm getting

![exposure_00000001_0000010](https://user-images.githubusercontent.com/10824158/226741960-494e4dd8-78af-49ca-9e95-c4e09ea7c7b8.png)
![exposure_00000001_0000080](https://user-images.githubusercontent.com/10824158/226741968-a8680a69-4c2c-40e5-983a-016c0a4feb3a.png)
![exposure_00000001_0000090](https://user-images.githubusercontent.com/10824158/226741970-862c4ae5-05dd-4285-a138-e424273d0580.png)
![exposure_00000001_0000100](https://user-images.githubusercontent.com/10824158/226741973-3497c724-3bc4-49f5-8502-60c3e9b2bbe9.png)

which one is the correct one?

**Comment by ieee8023** [comment]
What are you trying to do? That script simulates changes to the image to produce different results.

Do you want this script instead? https://github.com/mlmed/torchxrayvision/blob/master/scripts/process_image.py

**Comment by Moheeb77** [comment]
I'm checking the predection accuracy for the 18 diseases and trying to compare the accuracy with other research

**Comment by ieee8023** [comment]
You can see benchmark numbers here: https://github.com/mlmed/torchxrayvision/blob/master/BENCHMARKS.md

And those results were computed using this script: https://github.com/mlmed/torchxrayvision/blob/master/scripts/model_calibrate.py

**Comment by ieee8023** [comment]
Let me know if this issue is not resolved. I'll close the issue for now.

**Comment by santosh9sanjeev** [comment]
Hi.
Great work!
I wanted to know where is the benchmark on the MIMIC-CXR dataset?

**Comment by ieee8023** [comment]
Maybe this is what you aare looking for? https://github.com/mlmed/torchxrayvision/blob/master/BENCHMARKS.md

If not, please open a new issue: https://github.com/mlmed/torchxrayvision/issues/new

**Comment by santosh9sanjeev** [comment]
Yes I checked it, but cant find for MIMIC-CXR. Can you pls let me know where can I find it for mimic-cxr? . Sure will open a new one.

Thank you!
