### ISSUE TITLE
Add Montgomery and Shenzhen tuberculosis datasets

### ISSUE THREAD

**Issue by ieee8023** [mlmed/torchxrayvision#13]
https://openi.nlm.nih.gov/faq#collection

https://academictorrents.com/details/ac786f74878a5775c81d490b23842fd4736bfe33

https://academictorrents.com/details/462728e890bd37c05e9439c885df7afc36209cc8

Citation: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4256233/

**Comment by parsatorb** [comment]
On it!

**Comment by ieee8023** [comment]
I made a bunch of changes to it so it matches the interface on the other dataloaders (eg. dataset.labels and dataset.pathologies
