### ISSUE TITLE
Some questions about the 18 class

### ISSUE THREAD

**Issue by Liqq1** [mlmed/torchxrayvision#141]
Thank you for your contribution. I'd like to ask, during the process of multi-classification, are these fixed 18 classes the only ones available? I think this may not be very reasonable. In many cases, the current X-ray images are labeled as 'Normal' or 'No finding,' and all the classes here represent pathological conditions.
```
{'Atelectasis': 0.32797316,
 'Consolidation': 0.42933336,
 'Infiltration': 0.5316924,
 'Pneumothorax': 0.28849724,
 'Edema': 0.024142697,
 'Emphysema': 0.5011832,
 'Fibrosis': 0.51887786,
 'Effusion': 0.27805611,
 'Pneumonia': 0.18569896,
 'Pleural_Thickening': 0.24489835,
 'Cardiomegaly': 0.3645515,
 'Nodule': 0.68982,
 'Mass': 0.6392845,
 'Hernia': 0.00993878,
 'Lung Lesion': 0.011150705,
 'Fracture': 0.51916164,
 'Lung Opacity': 0.59073937,
 'Enlarged Cardiomediastinum': 0.27218717}
```
Thank you in advance. I am looking forward to hearing from you!

**Comment by ieee8023** [comment]
> are these fixed 18 classes the only ones available?

For the code models that is what they currently predict. There are other baseline models that predict race and age and segment anatomy: https://mlmed.org/torchxrayvision/models.html

> the current X-ray images are labeled as 'Normal' or 'No finding,'

I will keep an eye out for models that predict normal but I am not aware of any at the moment.
