### ISSUE TITLE
The use of ResNetAE

### ISSUE THREAD

**Issue by Eldo-rado** [mlmed/torchxrayvision#142]
Thank you for the code. I have encountered some problems while using it. I hope you can help me. My code is as follows:

```
img_path = '0.png'
img = skimage.io.imread(img_path)
img = xrv.datasets.normalize(img, 255) 

if len(img.shape) > 2:
    img = img[:, :, 0]
if len(img.shape) < 2:
    print("error, dimension lower than 2 for image")

img = img[None, :, :]
transforms = torchvision.transforms.Compose([xrv.datasets.XRayCenterCrop(), xrv.datasets.XRayResizer(224)])
img = transforms(img)
img = torch.from_numpy(img).unsqueeze(0)
ae = xrv.autoencoders.ResNetAE(weights="101-elastic")
out= ae(img)
img_r = out['out'].detach().numpy()

im = Image.fromarray(img_r[0][0])
im = im.convert('L')
im.save("filename.jpg")
```

The Input：
<img width="224" alt="image" src="https://github.com/mlmed/torchxrayvision/assets/128444206/ad0f29a8-55be-4957-be9b-2233757e6ff3">
The output：
<img width="266" alt="image" src="https://github.com/mlmed/torchxrayvision/assets/128444206/ba7a8524-0b8e-40a6-aac8-6c0e3c1252a7">

My output looks wrong. Am I making a mistake in the code? 😢

**Comment by ieee8023** [comment]
The image saving step is not working as expected because the pixel range of the output is -1024,1024. This works:

```python
# transform from -1024,1024 to 0,1
img_r = np.clip((img_r[0][0]+1024)/2048,0,1)
# convert to 8 bit values 0,255
skimage.io.imsave("test.png",(img_r*225).astype(np.uint8))
```
