### ISSUE TITLE
How to solve AttributeError: partially initialized module 'torchxrayvision' has no attribute 'datasets' (most likely due to a circular import)

### ISSUE THREAD

**Issue by tsongsun** [mlmed/torchxrayvision#146]
I have successfully installed the torchxrayvision library, but when I run the test program, I encounter an error message.

import torchxrayvision as xrv
import skimage, torch, torchvision

img = skimage.io.imread("16747_3_1.jpg")
img = xrv.datasets.normalize(img, 255) # convert 8-bit image to [-1024, 1024] range
img = img.mean(2)[None, ...] # Make single color channel

transform = torchvision.transforms.Compose([
    xrv.datasets.XRayCenterCrop(),
    xrv.datasets.XRayResizer(224),
])

img = transform(img)
img = torch.from_numpy(img)

model = xrv.models.DenseNet(weights="densenet121-res224-all")
outputs = model(img[None,...]) # or model.features(img[None,...])

dict(zip(model.pathologies, outputs[0].detach().numpy()))

**Comment by ieee8023** [comment]
It may be a path issue. Are you running it from inside the scripts folder? Is there a folder in the current directory with the name `torchxrayvision` ?

**Comment by tsongsun** [comment]
> It may be a path issue. Are you running it from inside the scripts folder? Is there a folder in the current directory with the name `torchxrayvision` ?Thank you for your reply, the problem is solved

**Comment by tsongsun** [comment]
> It may be a path issue. Are you running it from inside the scripts folder? Is there a folder in the current directory with the name `torchxrayvision` ?

Thank you for your reply, the problem is solved

**Comment by croraf** [comment]
I have the same problem, I'm running it from the folder where the script is. I have similar script in the same folder which doesn't give the same error but has the same line of code.

**Comment by croraf** [comment]
I had torchxrayvision in parent folder. Which gets resolved instead of the pip library.

For some reason the other script from the same folder resolved correctly. Strange. Now it works after rename of `torchxrayvision` from the parent folder.
