### ISSUE TITLE
BBox Pulmonary Fibrosis missing for VinBig Data set 

### ISSUE THREAD

**Issue by ajb8866** [mlmed/torchxrayvision#153]
Hello, I'd like to know why Pulmonary Fibrosis did not have a mask on the paper or in the GitHub. It was a reasonably large occurrence for that dataset, and it seems odd that 4655 classification instances were not labeled when included as positive instances. Other lesions/Lung Lesions were not included with the Bbox mask but were smaller, with 2203 occurrences.

**Comment by ieee8023** [comment]
Good catch. There was an issue where 'Pulmonary Fibrosis' != 'Pulmonary fibrosis' that is resolved with PR https://github.com/mlmed/torchxrayvision/pull/154

**Comment by ajb8866** [comment]
Would you happen to know the correct number of fibrosis Bboxes?

**Comment by ieee8023** [comment]
Here is how I computed it:
```python3
d_vin = xrv.datasets.VinBrain_Dataset(...)

# rawcsv is the file that comes with the dataset which has multiple annotations per image by different annotators. 
d_vin.rawcsv.class_name.str.contains('fibrosis').sum()
# 4655

# If we look at all annotations for fibrosis and then count the unique images they belong to:
len(d_vin.rawcsv[d_vin.rawcsv.class_name.str.contains('fibrosis')].groupby('image_id'))
# 1617

# and a sanity check that the has_masks column of the .csv (each row is a sample in the dataset) has a mask present. This doesn't have to be equal though but it is a good sign that it is.
d_vin.csv[d_vin.csv.class_name.str.contains('fibrosis')].has_masks.sum()
# 1617

```

**Comment by ajb8866** [comment]
Thank you close my issue.

**Comment by ajb8866** [comment]
Thank you, you can close out the issue now.
