### ISSUE TITLE
Training Script

### ISSUE THREAD

**Issue by amitbcp** [mlmed/torchxrayvision#21]
Are you using a the Merged Dataset for training ? I was not able to find the training script for the pre-trained models provided.

**Comment by ieee8023** [comment]
It is here: https://github.com/mlmed/torchxrayvision/blob/master/scripts/train_model.py

If you pass in a dataset name like "pcnih" it will load the of and noh datasets and merge them together.

**Comment by amitbcp** [comment]
Thanks @ieee8023 . I don't know how I missed it.
