### ISSUE TITLE
The  train/val/test split of datasets

### ISSUE THREAD

**Issue by FrankZhangRp** [mlmed/torchxrayvision#24]
Firstly, thanks a lot for your sharing code! 

I want to compare the performance on traditional setting (train on NIH and test on NIH) and leave one out setting (train on PC+MIMIC-CXR+CheXpert and test on NIH). But in 'torchxrayvision' we only get a whole dataset.  The comparison between leave one out setting and other papers' traditional setting are unfair because the test data are different(my understanding is the traditional setting use a small part of the dataset for testing and leave one out setting use the whole dataset for testing), this problem confuses me these days.

I find in the Figure 2 of your paper 'On the limits of cross-domain generalization in automated X-ray prediction'(MIDL 2020), your team conducts the comparison between 'training domain only', 'all other domains' and 'all domains'. Could you please share how to do the comparison, what's your strategy on datasets split.

Thank you!

**Comment by ieee8023** [comment]
The code to do the training/test split we used is here: https://github.com/mlmed/torchxrayvision/blob/master/scripts/train_model.py#L120-L142

And then the validation is cut out of the training data.

In that paper we train on the training slices of the datasets and test on the testing slices of the other datasets. So a single sample is never used for training and testing anywhere. (Unless the same image is used in multiple datasets)

**Comment by FrankZhangRp** [comment]
So all the datasets will be split into train/test parts with no overlap. Thanks a lot!

**Comment by ieee8023** [comment]
> From the code, the train/test split is 50%/50%， is it the default split setting?

Yes.

**Comment by FrankZhangRp** [comment]
Thanks a lot!
