### ISSUE TITLE
xrv.models.DenseNet(weights="all").cuda() problem in new update

### ISSUE THREAD

**Issue by dara1400** [mlmed/torchxrayvision#26]
Hello
Thanks for great repo

It seems you recently updated your codes, 
This error happens when i try to load pretrained net:

xrv.models.DenseNet(weights="all").cuda()

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in __getattr__(self, name)
    770                 return modules[name]
    771         raise ModuleAttributeError("'{}' object has no attribute '{}'".format(
--> 772             type(self).__name__, name))
    773 
    774     def __setattr__(self, name: str, value: Union[Tensor, 'Module']) -> None:

ModuleAttributeError: 'BatchNorm2d' object has no attribute '_non_persistent_buffers_set'

**Comment by ieee8023** [comment]
Ok I see it. It seems to be related to a new version of torchvision or torch. I tested it with torchvision 0.6.1 and it worked so you can downgrade to that. I'll look more into it today.

**Comment by dara1400** [comment]
I have downgraded as:
!pip install  torchvision==0.6.1 

now this error happened:

The NVIDIA driver on your system is too old (found version 10010).
Please update your GPU driver by downloading and installing a new
version from the URL: http://www.nvidia.com/Download/index.aspx
Alternatively, go to: https://pytorch.org to install
a PyTorch version that has been compiled with your version
of the CUDA driver.

Also I forgot to mention, I am using google colab

**Comment by ieee8023** [comment]
I have a fix. I am pushing in in 5 min.

**Comment by ieee8023** [comment]
It is the same issue and solution here: https://github.com/pytorch/pytorch/issues/42242

**Comment by ieee8023** [comment]
Ok the version 0.0.13 should fix it.

**Comment by dara1400** [comment]
Thanks a lot
I am using pip to install torchxrayvision,
Is the new upgrade applied to it?

**Comment by dara1400** [comment]
Thanks a lot
It is working well.

**Comment by Jen2351** [comment]
Hi there, 

I have the same issue right now. I run this line in Spyder and then it shows the error "AttributeError: module 'torchxrayvision' has no attribute 'models'". The version of torchxrayvision is 0.0.24, torchvision is 0.9.0 and torch is 1.8.0. I have tried to downgrade the torchxrayvision to 0.0.23, but it did not help.

**Comment by ieee8023** [comment]
@Jen2351 maybe you have a folder called torchxrayvision in your path that is confusing the import?
