### ISSUE TITLE
Test csv on CheX_Dataset

### ISSUE THREAD

**Issue by matteoguarrera** [mlmed/torchxrayvision#39]
https://github.com/mlmed/torchxrayvision/blob/7e53f0606986562f17a1ffd9f31d006756eff78d/torchxrayvision/datasets.py#L888
It seems that CheX_Dataset was designed only for loading the train.csv 
I've tried to use it also with valid.csv but I got an error, since it split the path using the constant string "train/".

The following lines should fix the problem!

```python
    # patientid
    if 'train' in csvpath:
        patientid = self.csv.Path.str.split("train/", expand=True)[1]

    elif 'valid' in csvpath:
        patientid = self.csv.Path.str.split("valid/", expand=True)[1]
    else:
        raise NotImplemented
```

Thank you so much!

**Comment by ieee8023** [comment]
Thanks! Do you want to submit a full request so you show up on the repo history? Otherwise I can make the edit. Let me know!

**Comment by matteoguarrera** [comment]
I have submitted the request! I'm glad to help in this project
