### ISSUE TITLE
Normalization for the probability thresholds

### ISSUE THREAD

**Issue by adam-dziedzic** [mlmed/torchxrayvision#44]
https://github.com/mlmed/torchxrayvision/blob/3b64cbe87ca6672ead074d363e360059b93b49ae/torchxrayvision/models.py#L245

Shouldn't this be computed as: outputs_new[mask_gt] = 0.5 + 0.5 * (outputs[mask_gt] - op_threshs[mask_gt]) / (1 - op_threshs[mask_gt])

instead of outputs_new[mask_gt] = 1.0 - ((1.0 - outputs[mask_gt]) / ((1 - op_threshs[mask_gt]) * 2))

In your computation, if outputs[mask_gt] == op_threshs[mask_gt], then the computed new value outputs_new[mask_gt] < 0.

**Comment by ieee8023** [comment]
They both compute to be 0.5 if `outputs[mask_gt] == op_threshs[mask_gt]` for me. 

![Screen Shot 2021-02-15 at 5 25 25 PM](https://user-images.githubusercontent.com/446367/107998291-cda5f780-6fb2-11eb-932e-cc437e57ba3d.png)

I haven't thought about this in a long time so maybe I am overlooking something?

**Comment by adam-dziedzic** [comment]
My bad! These expressions are equivalent.

**Comment by ieee8023** [comment]
Thanks for looking into the details! It is what will make this project valuable to have the core code verified by everyone!
