### ISSUE TITLE
Dataset class problem

### ISSUE THREAD

**Issue by Khanhman29** [mlmed/torchxrayvision#46]
Hi there,
thanks for your repo,
I run dataset = xrv.datasets.StonyBrookCOVID_Dataset() in Colab and it show the error : AttributeError: module 'torchxrayvision.datasets' has no attribute 'StonyBrookCOVID_Dataset' . Is there any solution to fix this error?

**Comment by ieee8023** [comment]
That was my mistake. I forgot to push a new version to pip. It is in version 0.0.25

You can run `pip install torchxrayvision --upgrade` to get the new version.
