### ISSUE TITLE
Histogram of scores produced by chex model

### ISSUE THREAD

**Issue by lkourti** [mlmed/torchxrayvision#49]
Hello! We are using your chex model to evaluate the whole CheXpert-v1.0-small dataset. Here are the histograms of scores per disease:
![image](https://user-images.githubusercontent.com/55799983/118858923-3eed9300-b89f-11eb-83b7-35dee5429a9e.png)
We were wondering if you could help us understand the jumps that happen on 0.5 for every disease.
We read the relevant section in the paper, where you dicsuss the calibration of the model, but we don't fully understand how to connect this with the above question.
Thank you in advance!

**Comment by ieee8023** [comment]
You can run the models uncalibrated if you set `model.op_threshs = None` as seen in this script: https://github.com/mlmed/covid-severity/blob/master/predict_severity.py

**Comment by lkourti** [comment]
That's helpful, thank you!
