### ISSUE TITLE
VinBigData Dataset

### ISSUE THREAD

**Issue by RedMoon32** [mlmed/torchxrayvision#51]
Hello! Do you plan in the future to add kaggle 'VinBigData Chest X-ray'? Or it is too label-noisy?

**Comment by ieee8023** [comment]
It is there! 

d_vin = xrv.datasets.VinBrain_Dataset(imgpath=".../train",
                                      csvpath=".../train.csv")

We need better documentation, sorry! I just added it to the readme.
