### ISSUE TITLE
More in depth documentation

### ISSUE THREAD

**Issue by SystematicError** [mlmed/torchxrayvision#58]
Hey I'm new to the library and it looks fantastic however after some time fiddling around and reading documentation its still  a bit confusing to me, I'm trying to scan a image and get the predictions on the model which was trained for all diseases however couldn't get it to work. I understand the project is still under construction but more examples and documentation would help a lot!

**Comment by ieee8023** [comment]
Thanks!

We definitely need better documentation so we have been working on a paper! It is still in preparation but you can read the live draft here: https://www.overleaf.com/read/gksfksptgjhy

Although currently it doesn't explain what you want to do so I can tell you here! I think you are looking for the script: 
https://github.com/mlmed/torchxrayvision/blob/master/scripts/process_image.py which you can run like this:

```
$ python3 process_image.py ../tests/00000001_000.png 
{'preds': {'Atelectasis': 0.50577986,
           'Cardiomegaly': 0.62151504,
           'Consolidation': 0.31243291,
           'Edema': 0.21286593,
           'Effusion': 0.39427394,
           'Emphysema': 0.503361,
           'Enlarged Cardiomediastinum': 0.43138638,
           'Fibrosis': 0.5401596,
           'Fracture': 0.28907463,
           'Hernia': 0.01267795,
           'Infiltration': 0.5220189,
           'Lung Lesion': 0.21828471,
           'Lung Opacity': 0.36826077,
           'Mass': 0.4104132,
           'Nodule': 0.5091791,
           'Pleural_Thickening': 0.5104176,
           'Pneumonia': 0.18006416,
           'Pneumothorax': 0.30677897}}
```

**Comment by SystematicError** [comment]
Thanks! Initially I was using `xray_models.py` but got confused, just spent an hour fiddling with the code and it worked perfectly.

**Comment by ieee8023** [comment]
We have a paper now with (hopefully) very in depth documentation! Let us know if there are still some unanswered questions

https://arxiv.org/abs/2111.00595
