### ISSUE TITLE
cannot modify number of classes

### ISSUE THREAD

**Issue by ASKanse** [mlmed/torchxrayvision#59]
I see that the num_classes attribute is not actually a custom input because of this line in models.py 
https://github.com/mlmed/torchxrayvision/blob/8554200ecde1b847b4ebca6d7f02b95715d9df4c/torchxrayvision/models.py#L148

will this be added later?

Thanks

**Comment by ieee8023** [comment]
That is only when loading pre-trained weights. So the number of outputs it fixed for each set of weights. 

You can specify num_classes in the constructor if you load a randomly initialized model.
