### ISSUE TITLE
Disabling dataset summary statistics

### ISSUE THREAD

**Issue by santoshg117** [mlmed/torchxrayvision#74]
Is there a way to disable the following output appearing every time a command is being executed?

![image](https://user-images.githubusercontent.com/74808108/140447756-d9b1301b-478e-417f-b38b-cb8840d4cc12.png)

**Comment by ieee8023** [comment]
What command are you executing? That will output happen when you do something like print(dataset) and str() is called on the object.

**Comment by ieee8023** [comment]
Closing this for now. Please reopen if the issue was not resolved.
