### ISSUE TITLE
Confusion about input image format

### ISSUE THREAD

**Issue by antonie-z** [mlmed/torchxrayvision#93]
Hello author, thank you for sharing the code! But I have some questions, I found that the input format of the chest image has been changed from 3 channels to single channel, what is the benefit of doing this? Does this have any effect on the results? Looking forward to your insights!

**Comment by ieee8023** [comment]
I am not aware of any CXR image which has 3 channels. The X-ray sensor is typically just a single intensity. Can you provide more into about the data you are trying to work with?

**Comment by antonie-z** [comment]
Sorry I have understood cv2 default parameters read CXR into three channels, thank you for answering this simple question for me

**Comment by ieee8023** [comment]
No problem! Feel free to ask more questions as you continue with your project!
